apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-payment-svc
  name: api-payment-loadbalancer-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: api-pod-payment
  type: LoadBalancer
