apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: default
  labels:
    name: db-config
data:
  DYNAMODB_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "ASIAR3F4HGIBPL36GJYS"
  AWS_SECRET_ACCESS_KEY: "5K5bwVx3kqDoYBP19EC71jw0qjahRqYZAXci9DTd"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEBMaCXVzLXdlc3QtMiJGMEQCIFXRIPq8awE3NEykqgcfyP/lQ6cWS1ezOZc+beQc/+P4AiA2FoW/8EF86UHx11OvV0cDU780DzIwhWCk9XXiRTiC0iqxAgg8EAAaDDEyNzA5NjI3MTM2MiIMx3A5XNNAr+ymvzNaKo4CiGSfZtJY/ZTO/bizoKoHaTLX53zf7MC7xJbkMij0wV0kRT1OapydGebeQSBDwHublQSu6V9okMoWR9f4X8vw5yLso/CjFF86zhRG1DUcG3LgSadecNXJ9dKbVQhW1kkve64I/9khWau3UIUtkHDyOxsLlzxO3xBhFZfwwweUStgOhsvyZYCq7miAOhZ10e7gWKJQOZzWWab7MCZ2Pl9V5Z5l1MjQ8GrcxKpfH3GY748BNMZyE3zyT0JJ0xlLcfPLlBADbTgMiqVfbWacW5CfvQxXYPd9BpPJTDzI9R96LnYekossWLlS6MPoFsUMTpZtig/paif/Y+RBFSoNGlx2/5GDdvt81ee8QvTNs8x4MM/0v70GOp4BjF8jh3inLQ8kVl69d0pQxmh5z01kjpm8CCD4Bzva55WhQZCWbTtdTN4/K1CTmUy+vvoB2W2ZpVlPqnYnSLG5H0740dgx0a/lKNgWKoByu5KyRn4hR60daLJYThV80o+b+ZOSQzaiT3f2PedeAQ5kDZEJZeUuX/e1QaV8L9zgHyMbZRxZVpIXMgP1SzXnS3LcWEFVdFAgriALP3R6RZA="
  ECR_API: 127096271362.dkr.ecr.us-east-1.amazonaws.com/Fastfood-Order-API:latest
