apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: default
  labels:
    name: db-config
data:
  MYSQL_URL: jdbc:mysql://terraform-20250216171047441900000001.cc6lgc3nfn4u.us-east-1.rds.amazonaws.com:3306/lanchonetedb
  MYSQL_USERNAME: sa
  MYSQL_PASSWORD: password123
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
  DYNAMODB_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
  ECR_API: 127096271362.dkr.ecr.us-east-1.amazonaws.com/fastfood-order-api:latest
